/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.IngressosJa.view;

import br.com.IngressosJa.controller.Autentica;
import br.com.IngressosJa.controller.EventoController;
import br.com.IngressosJa.model.Evento;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author diogo
 */
public class TelaCompraIngressos extends javax.swing.JFrame {
    Autentica aut = new Autentica();
    ArrayList<Evento> eve;
    /**
     * Creates new form TelaCompraIngressos
     */
    public TelaCompraIngressos() {
        try {
            this.eve = new ArrayList<>(EventoController.buscaEventos());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro!! "+ex);
        }
        initComponents();
        this.preencheComboBox();
        this.jQuantosIngressos.setVisible(false);
        this.jQntIngressosSpinner.setVisible(false);
        //this.jPrecoTotal.setVisible(false);
        //System.out.println(aut.getMorOrVis());
      
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDadosEvento = new javax.swing.JPanel();
        jNomeEventoComboBox = new javax.swing.JComboBox();
        jQuantosIngressos = new javax.swing.JLabel();
        jQntIngressosSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jFinalizarCompraButton = new javax.swing.JButton();
        jSairButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDataEvento = new javax.swing.JLabel();
        jQuantidadeDisponivel = new javax.swing.JLabel();
        jPrecoMor = new javax.swing.JLabel();
        jPrecoVis = new javax.swing.JLabel();
        jLocalEvento = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDadosEvento.setBackground(new java.awt.Color(204, 204, 255));
        jDadosEvento.setPreferredSize(new java.awt.Dimension(900, 600));

        jNomeEventoComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jNomeEventoComboBoxItemStateChanged(evt);
            }
        });
        jNomeEventoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeEventoComboBoxActionPerformed(evt);
            }
        });

        jQuantosIngressos.setText("Quantos Ingressos:");

        jQntIngressosSpinner.setPreferredSize(new java.awt.Dimension(100, 22));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Compra de Ingressos");

        jFinalizarCompraButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Clear Green Button.png"))); // NOI18N
        jFinalizarCompraButton.setText("Finalizar Compra");
        jFinalizarCompraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinalizarCompraButtonActionPerformed(evt);
            }
        });

        jSairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancel Red Button.png"))); // NOI18N
        jSairButton.setText("Sair");
        jSairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Escolha o Evento:");

        javax.swing.GroupLayout jDadosEventoLayout = new javax.swing.GroupLayout(jDadosEvento);
        jDadosEvento.setLayout(jDadosEventoLayout);
        jDadosEventoLayout.setHorizontalGroup(
            jDadosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDadosEventoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFinalizarCompraButton)
                .addGap(77, 77, 77)
                .addComponent(jSairButton)
                .addGap(68, 68, 68))
            .addGroup(jDadosEventoLayout.createSequentialGroup()
                .addGroup(jDadosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDadosEventoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jNomeEventoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDadosEventoLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel3))
                    .addGroup(jDadosEventoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jDadosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jQuantidadeDisponivel)
                            .addComponent(jDataEvento)
                            .addComponent(jPrecoMor)
                            .addComponent(jPrecoVis)
                            .addComponent(jLocalEvento)))
                    .addGroup(jDadosEventoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jQuantosIngressos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jQntIngressosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(jDadosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDadosEventoLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel4)
                    .addContainerGap(774, Short.MAX_VALUE)))
        );
        jDadosEventoLayout.setVerticalGroup(
            jDadosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDadosEventoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(82, 82, 82)
                .addComponent(jNomeEventoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jDataEvento)
                .addGap(18, 18, 18)
                .addComponent(jQuantidadeDisponivel)
                .addGap(18, 18, 18)
                .addComponent(jPrecoMor)
                .addGap(18, 18, 18)
                .addComponent(jPrecoVis)
                .addGap(18, 18, 18)
                .addComponent(jLocalEvento)
                .addGap(24, 24, 24)
                .addGroup(jDadosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQuantosIngressos)
                    .addComponent(jQntIngressosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addGroup(jDadosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFinalizarCompraButton)
                    .addComponent(jSairButton))
                .addGap(40, 40, 40))
            .addGroup(jDadosEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDadosEventoLayout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(jLabel4)
                    .addContainerGap(471, Short.MAX_VALUE)))
        );

        jMenu1.setText("Arquivo");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre");
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDadosEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDadosEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jFinalizarCompraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinalizarCompraButtonActionPerformed
        try {
            // TODO add your handling code here:
            JOptionPane.showMessageDialog(this, "Preço Total: "+calculaPreco(EventoController.buscaEventos().get(jNomeEventoComboBox.getSelectedIndex()).getIngressos().getPrecoMor(),
                EventoController.buscaEventos().get(jNomeEventoComboBox.getSelectedIndex()).getIngressos().getPrecoVis(),
                this.jQntIngressosSpinner.getValue().toString())+"\n"+aut.getNomeUser()+", seus ingressos foram comprados com sucesso.");
            
            if(EventoController.decrementaIngressos(this.jQntIngressosSpinner.getValue().toString(), 
                    this.jNomeEventoComboBox.getSelectedItem().toString())) dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro!! "+ex);
        }
    }//GEN-LAST:event_jFinalizarCompraButtonActionPerformed

    private void jSairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairButtonActionPerformed
        dispose();
    }//GEN-LAST:event_jSairButtonActionPerformed

    private void jNomeEventoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeEventoComboBoxActionPerformed
        try {
            this.jDataEvento.setText("Data do evento: \t"+/*EventoController.buscaEventos()*/eve.get(jNomeEventoComboBox.getSelectedIndex()).getDataEvento());
            this.jQuantidadeDisponivel.setText("Quantidade: \t"+/*EventoController.buscaEventos()*/eve.get(jNomeEventoComboBox.getSelectedIndex()).getIngressos().getQuantidadeDeIngresso());
            this.jPrecoMor.setText("Morador: \t"+/*EventoController.buscaEventos()*/eve.get(jNomeEventoComboBox.getSelectedIndex()).getIngressos().getPrecoMor());
            this.jPrecoVis.setText("Visitante: \t"+/*EventoController.buscaEventos()*/eve.get(jNomeEventoComboBox.getSelectedIndex()).getIngressos().getPrecoVis());
            this.jLocalEvento.setText("Local: \t"+/*EventoController.buscaEventos()*/eve.get(jNomeEventoComboBox.getSelectedIndex()).getLocalEvento());
            this.jQntIngressosSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, /*EventoController.buscaEventos()*/eve.get(jNomeEventoComboBox.getSelectedIndex()).getIngressos().getQuantidadeDeIngresso(), 1));
            this.jQuantosIngressos.setVisible(true);
            this.jQntIngressosSpinner.setVisible(true);
            //this.jPrecoTotal.setVisible(true);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro!! "+ex);
        }

    }//GEN-LAST:event_jNomeEventoComboBoxActionPerformed

    private void jNomeEventoComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jNomeEventoComboBoxItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jNomeEventoComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompraIngressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompraIngressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompraIngressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompraIngressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompraIngressos().setVisible(true);
                
            }
        });
    }
    
    public void preencheComboBox(){
        try{
            //ArrayList<Evento> eve = new ArrayList<>(EventoController.buscaEventos());
            eve = EventoController.buscaEventos();
            for(int i =0; i<eve.size(); i++){
            this.jNomeEventoComboBox.addItem(eve.get(i).getNomeEvento());
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro na obtenção dos parametros!");
            dispose();
            e.printStackTrace();
        }
    }
    
    public int calculaPreco(int mor, int vis, String quant){
        if(aut.getMorOrVis().equals("-1")){
            return vis*Integer.parseInt(quant);
        }else{
            return mor*Integer.parseInt(quant);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jDadosEvento;
    private javax.swing.JLabel jDataEvento;
    private javax.swing.JButton jFinalizarCompraButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLocalEvento;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JComboBox jNomeEventoComboBox;
    private javax.swing.JLabel jPrecoMor;
    private javax.swing.JLabel jPrecoVis;
    private javax.swing.JSpinner jQntIngressosSpinner;
    private javax.swing.JLabel jQuantidadeDisponivel;
    private javax.swing.JLabel jQuantosIngressos;
    private javax.swing.JButton jSairButton;
    // End of variables declaration//GEN-END:variables
}
