/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.IngressosJa.view;

import br.com.IngressosJa.controller.EventoController;
import br.com.IngressosJa.model.Evento;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author thiago
 */
public class TelaRemoveEvento extends javax.swing.JFrame {

    /**
     * Creates new form RemoveEvento
     */
    public TelaRemoveEvento() {
        initComponents();
        this.preencheComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNomeEventoComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jConfirma = new javax.swing.JButton();
        jSair = new javax.swing.JButton();
        jLocal = new javax.swing.JLabel();
        jData = new javax.swing.JLabel();
        jIngressos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        /*
        jNomeEventoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        */
        jNomeEventoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeEventoComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Escolha um evento a ser removido:");

        jConfirma.setText("OK");
        jConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmaActionPerformed(evt);
            }
        });

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });

        jLocal.setText("Local");

        jData.setText("Data");

        jIngressos.setText("Ingressos Disponíveis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jIngressos)
                    .addComponent(jData)
                    .addComponent(jLocal)
                    .addComponent(jNomeEventoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jSair, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNomeEventoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLocal)
                .addGap(18, 18, 18)
                .addComponent(jData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jIngressos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSair, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomeEventoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeEventoComboBoxActionPerformed
        // TODO add your handling code here:
        try {
            
            this.jData.setText("Data: "+EventoController.buscaEventos().get(jNomeEventoComboBox.getSelectedIndex()).getDataEvento());
            this.jLocal.setText("Local: "+EventoController.buscaEventos().get(jNomeEventoComboBox.getSelectedIndex()).getLocalEvento());
            this.jIngressos.setText("Ingressos Disponíveis: "+EventoController.buscaEventos().get(jNomeEventoComboBox.getSelectedIndex()).getIngressos().getQuantidadeDeIngresso());
            /*String gerente; 
            if(MoradorController.buscaMoradores().get(jNomeUsuarioComboBox.getSelectedIndex()).getGerente()==1) gerente = "Sim";
            else{gerente = "Não";}
            
            this.jCPF.setText("CPF: "+MoradorController.buscaMoradores().get(jNomeUsuarioComboBox.getSelectedIndex()).getCpf());
            this.jNome.setText("Login: "+MoradorController.buscaMoradores().get(jNomeUsuarioComboBox.getSelectedIndex()).getLogin());
            this.jGerente.setText("Gerente: "+gerente);*/
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro "+ex);
        }
    }//GEN-LAST:event_jNomeEventoComboBoxActionPerformed

    private void jConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmaActionPerformed
        // TODO add your handling code here:
        try{
            if(EventoController.removeEvento(this.jNomeEventoComboBox.getSelectedItem().toString())){
                JOptionPane.showMessageDialog(this, "Evento removido com sucesso!");
                dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro na remoção");
            }
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_jConfirmaActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRemoveEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRemoveEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRemoveEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRemoveEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRemoveEvento().setVisible(true);
            }
        });
    }

    public void preencheComboBox(){
        try{
            ArrayList<Evento> eve = new ArrayList<>(EventoController.buscaEventos());
            eve = EventoController.buscaEventos();
            for(int i =0; i<eve.size(); i++){
            this.jNomeEventoComboBox.addItem(eve.get(i).getNomeEvento());
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro na obtenção dos parametros!");
            dispose();
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jConfirma;
    private javax.swing.JLabel jData;
    private javax.swing.JLabel jIngressos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLocal;
    private javax.swing.JComboBox<String> jNomeEventoComboBox;
    private javax.swing.JButton jSair;
    // End of variables declaration//GEN-END:variables
}
