/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.IngressosJa.view;

import br.com.IngressosJa.controller.VisitanteController;
import br.com.IngressosJa.model.Visitante;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author thiago
 */
public class TelaRemoveVisitante extends javax.swing.JFrame {
    ArrayList<Visitante> vis;
    /**
     * Creates new form TelaRemoveVisitante
     */
    public TelaRemoveVisitante() {
        try {
            this.vis = new ArrayList<>(VisitanteController.buscaVisitantes());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro!! "+ex);
        }
        initComponents();
        this.preencheComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jNomeUsuarioComboBox = new javax.swing.JComboBox<>();
        jCPF = new javax.swing.JLabel();
        jSair = new javax.swing.JButton();
        jSelecao = new javax.swing.JButton();
        jCPFVinculado = new javax.swing.JLabel();
        jNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escolha um usuário a ser removido:");

        /*
        jNomeUsuarioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        */
        jNomeUsuarioComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNomeUsuarioComboBoxActionPerformed(evt);
            }
        });

        jCPF.setText("CPF");

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });

        jSelecao.setText("Selecionar");
        jSelecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelecaoActionPerformed(evt);
            }
        });

        jCPFVinculado.setText("CPF vinculado");

        jNome.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCPFVinculado)
                    .addComponent(jNome)
                    .addComponent(jCPF)
                    .addComponent(jNomeUsuarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jSelecao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jSair)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNomeUsuarioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCPFVinculado)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSelecao)
                    .addComponent(jSair))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNomeUsuarioComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNomeUsuarioComboBoxActionPerformed
        // TODO add your handling code here:
        try {
            this.jCPF.setText("CPF: "+/*VisitanteController.buscaVisitantes()*/vis.get(jNomeUsuarioComboBox.getSelectedIndex()).getCpf());
            this.jNome.setText("Login: "+/*VisitanteController.buscaVisitantes()*/vis.get(jNomeUsuarioComboBox.getSelectedIndex()).getLogin());
            this.jCPFVinculado.setText("CPF vinculado: "+/*VisitanteController.buscaVisitantes()*/vis.get(jNomeUsuarioComboBox.getSelectedIndex()).getCpfDoMorador());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro "+ex);
        }
    }//GEN-LAST:event_jNomeUsuarioComboBoxActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jSairActionPerformed

    private void jSelecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelecaoActionPerformed
        // TODO add your handling code here:
        try{
            if(VisitanteController.removeVisitante(this.jNomeUsuarioComboBox.getSelectedItem().toString(), /*VisitanteController.buscaVisitantes()*/vis.get(jNomeUsuarioComboBox.getSelectedIndex()).getCpf())){
                JOptionPane.showMessageDialog(this, "Visitante removido com sucesso");
                dispose();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro "+e);
        }
    }//GEN-LAST:event_jSelecaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRemoveVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRemoveVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRemoveVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRemoveVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRemoveVisitante().setVisible(true);
            }
        });
    }
    
     public void preencheComboBox(){
        try{
            //ArrayList<Visitante> vis = new ArrayList<>(VisitanteController.buscaVisitantes());
            vis = VisitanteController.buscaVisitantes();
            for(int i =0; i<vis.size(); i++){
                this.jNomeUsuarioComboBox.addItem(vis.get(i).getNome());
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro na obtenção dos parametros!");
            dispose();
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCPF;
    private javax.swing.JLabel jCPFVinculado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNome;
    private javax.swing.JComboBox<String> jNomeUsuarioComboBox;
    private javax.swing.JButton jSair;
    private javax.swing.JButton jSelecao;
    // End of variables declaration//GEN-END:variables
}
